# The pull request's title should be fulfilled the following pattern:
#
#     <type>[optional scope]: <description>
#
# ... where valid types and scopes can be found below; for example:
#
#     build(maven): One level down for native profile
#
# More about configurations on https://github.com/Ezard/semantic-prs#configuration

enabled: true

titleOnly: true

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - deps

targetUrl: https://github.com/foyer-rs/foyer/blob/main/.github/semantic.yml
