{
 "title": "foyer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Hybrid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Op",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - hybrid - {{op}}"
    }
   ]
  },
  {
   "title": "Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_hybrid_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p50 - {{name}} - hybrid - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_hybrid_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p90 - {{name}} - hybrid - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_hybrid_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p99 - {{name}} - hybrid - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_hybrid_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "pmax - {{name}} - hybrid - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_hybrid_op_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_hybrid_op_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - hybrid - {{op}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_hybrid_op_total{op=\"hit\"}[$__rate_interval])) by (name) / (sum(rate(foyer_hybrid_op_total{op=\"hit\"}[$__rate_interval])) by (name) + sum(rate(foyer_hybrid_op_total{op=\"miss\"}[$__rate_interval])) by (name)) ",
     "legendFormat": "{{name}} - hybrid - hit ratio"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Op",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - memory - {{op}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(foyer_memory_usage) by (name)",
     "legendFormat": "{{name}} - memory - usage (bytes)"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_memory_op_total{op=\"hit\"}[$__rate_interval])) by (name) / (sum(rate(foyer_memory_op_total{op=\"hit\"}[$__rate_interval])) by (name) + sum(rate(foyer_memory_op_total{op=\"miss\"}[$__rate_interval])) by (name)) ",
     "legendFormat": "{{name}} - memory - hit ratio"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Op",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p50 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p90 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p99 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "pmax - {{name}} - storage - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_op_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_op_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "Region Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(foyer_storage_region) by (name, type)",
     "legendFormat": "{{name}} - region - {{type}}"
    }
   ]
  },
  {
   "title": "Inner Op",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_inner_op_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "Inner Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_inner_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p50 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_inner_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p90 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_inner_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p99 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_inner_op_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "pmax - {{name}} - storage - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_inner_op_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_inner_op_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "Region Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(foyer_storage_region) by (name, type) * on(name) group_left() foyer_storage_region_size_bytes",
     "legendFormat": "{{name}} - region - {{type}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_total{op=\"hit\"}[$__rate_interval])) by (name) / (sum(rate(foyer_storage_op_total{op=\"hit\"}[$__rate_interval])) by (name) + sum(rate(foyer_storage_op_total{op=\"miss\"}[$__rate_interval])) by (name)) ",
     "legendFormat": "{{name}} - storage - hit ratio"
    }
   ]
  },
  {
   "title": "Serde Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p50 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p90 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "p99 - {{name}} - storage - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_entry_serde_duration_bucket[$__rate_interval])) by (le, name, op))",
     "legendFormat": "pmax - {{name}} - storage - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_entry_serde_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_entry_serde_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - storage - {{op}}"
    }
   ]
  },
  {
   "title": "LODC Buffer Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p50 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p90 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p99 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_lodc_buffer_efficiency_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "pmax - {{name}} - efficiency"
    },
    {
     "expr": "sum(rate(foyer_storage_lodc_buffer_efficiency_sum[$__rate_interval])) by (le, name) / sum(rate(foyer_storage_lodc_buffer_efficiency_count[$__rate_interval])) by (le, name)",
     "legendFormat": "pavg - {{name}} - efficiency"
    }
   ]
  },
  {
   "title": "LODC Recover Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_lodc_recover_duration_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p50 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_lodc_recover_duration_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p90 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_lodc_recover_duration_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "p99 - {{name}} - efficiency"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_lodc_recover_duration_bucket[$__rate_interval])) by (le, name)) ",
     "legendFormat": "pmax - {{name}} - efficiency"
    },
    {
     "expr": "sum(rate(foyer_storage_lodc_recover_duration_sum[$__rate_interval])) by (le, name) / sum(rate(foyer_storage_lodc_recover_duration_count[$__rate_interval])) by (le, name)",
     "legendFormat": "pavg - {{name}} - efficiency"
    }
   ]
  },
  { "title": "Storage (Disk)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_disk_io_total[$__rate_interval])) by (name, op)",
     "legendFormat": "{{name}} - disk io - {{op}}"
    }
   ]
  },
  {
   "title": "Disk IO Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p50 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p90 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "p99 - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_disk_io_duration_bucket[$__rate_interval])) by (le, name, op)) ",
     "legendFormat": "pmax - {{name}} - disk io - {{op}}"
    },
    {
     "expr": "sum(rate(foyer_storage_disk_io_duration_sum[$__rate_interval])) by (le, name, op) / sum(rate(foyer_storage_disk_io_duration_count[$__rate_interval])) by (le, name, op)",
     "legendFormat": "pavg - {{name}} - disk io - {{op}}"
    }
   ]
  },
  {
   "title": "Op Thoughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_disk_io_bytes[$__rate_interval])) by (foyer, op, extra) ",
     "legendFormat": "{{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  }
 ]
}