{
 "title": "foyer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Op",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_duration_count[$__rate_interval])) by (foyer, op, extra)",
     "legendFormat": "{{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Slow Op",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_slow_op_duration_count[$__rate_interval])) by (foyer, op, extra)",
     "legendFormat": "{{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p50 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p90 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p99 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "pmax - {{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Slow Op Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(foyer_storage_slow_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p50 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(foyer_storage_slow_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p90 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(foyer_storage_slow_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "p99 - {{foyer}} foyer storage - {{op}} {{extra}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(foyer_storage_slow_op_duration_bucket[$__rate_interval])) by (le, foyer, op, extra)) ",
     "legendFormat": "pmax - {{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Op Thoughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_bytes[$__rate_interval])) by (foyer, op, extra) ",
     "legendFormat": "{{foyer}} foyer storage - {{op}} {{extra}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(foyer_storage_total_bytes) by (foyer) ",
     "legendFormat": "{{foyer}} foyer storage"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(foyer_storage_op_duration_count{op=\"lookup\", extra=\"hit\"}[$__rate_interval])) by (foyer) / (sum(rate(foyer_storage_op_duration_count{op=\"lookup\", extra=\"hit\"}[$__rate_interval])) by (foyer) + sum(rate(foyer_storage_op_duration_count{op=\"lookup\", extra=\"miss\"}[$__rate_interval])) by (foyer)) ",
     "legendFormat": "{{foyer}} foyer storage"
    }
   ]
  }
 ]
}