name: License Checker

on:
  push:
    branches:
      - main
      - "forks/*"
      - release-*.*
    paths-ignore:
      - "website/**"
  pull_request:
    branches: 
      - main
      - "v*.*.*-rc"
      - release-*.*
    paths-ignore:
      - "website/**"
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Check License Header
      uses: apache/skywalking-eyes/header@v0.6.0
