name: Test deployment

on:
  pull_request:
    branches:
      - main
      - "v*.*.*-rc"
      - release-*.*
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "website/package.json"
      - name: Install dependencies
        working-directory: website
        run: npm ci
      - name: Test build website
        working-directory: website
        run: npm run build